import 'package:flutter/material.dart';

import 'subscription_plan_model.dart';

const List<PlanModel> defaultSubscriptionPlans = <PlanModel>[
  PlanModel(
    title: 'Daily Pass',
    markerColor: Color(0xFFF3B41A),
    borderColor: Color(0xFFF3B41A),
    background: LinearGradient(colors: [Color(0xFF073447), Color(0xFF073447)]),
    bullets: [
      'Access for one day',
      'Full access to the gym between 6:00 and 23:00',
    ],
    priceMain: '€10',
    amount: 10,
  ),
  PlanModel(
    title: 'Monthly Plan',
    markerColor: Color(0xFF4BCDC0),
    borderColor: Color(0xFF6A8C87),
    background: LinearGradient(colors: [Color(0xFF142733), Color(0xFF124331)]),
    bullets: [
      'Full access to the gym',
      'Renewable subscription with no commitment until cancellation',
    ],
    priceMain: '€40',
    priceAccent: '/ Month',
    accentColor: Color(0xFF4BCDC0),
    amount: 40,
    billingPeriod: 'monthly',
  ),
  PlanModel(
    title: '6-Month Plan',
    markerColor: Color(0xFFB45CFF),
    borderColor: Color(0xFF7A5D9A),
    background: LinearGradient(colors: [Color(0xFF2E1C44), Color(0xFF39214D)]),
    bullets: [
      'Gift: 1 Pro Factory T-shirt',
      'Full access to the gym',
      'Renewable subscription with a minimum commitment period of 6 months',
    ],
    priceMain: '€35',
    priceAccent: '/ Month',
    accentColor: Color(0xFFB45CFF),
    amount: 35,
    billingPeriod: 'monthly',
  ),
  PlanModel(
    title: '12-Month Plan',
    markerColor: Color(0xFFF39DB8),
    borderColor: Color(0xFF8D6675),
    background: LinearGradient(colors: [Color(0xFF4A2D39), Color(0xFF4A3139)]),
    bullets: [
      'Gift: 1 Pro Factory hoodie',
      'Full access to the gym',
      'Renewable subscription with a minimum commitment period of 12 months',
    ],
    priceMain: '€30',
    priceAccent: '/ Month',
    accentColor: Color(0xFFF39DB8),
    amount: 30,
    billingPeriod: 'monthly',
  ),
  PlanModel(
    title: '12-Month Plan Single\nPayment',
    markerColor: Color(0xFFF0C13F),
    borderColor: Color(0xFF8A7B4A),
    background: LinearGradient(colors: [Color(0xFF3A2E08), Color(0xFF433308)]),
    bullets: [
      'Gift: 1 Pro Factory hoodie',
      'Full access to the gym',
      'Renewable subscription for 12 months with no commitment.',
    ],
    priceMain: '€330/',
    note: 'Subscription with discount\nfor upfront payment',
    amount: 330,
    billingPeriod: 'yearly',
  ),
  PlanModel(
    title: 'Off-Peak 12-Month Plan',
    markerColor: Color(0xFFA7A7A7),
    borderColor: Color(0xFF626B76),
    background: LinearGradient(colors: [Color(0xFF191E2B), Color(0xFF20222D)]),
    bullets: [
      'Gift: 1 Pro Factory T-shirt',
      'Renewable subscription with a minimum commitment period of 12 months',
      'Access to the gym at the following times:\nMonday to Friday: From 6:00 to 8:30 From 13:00 to 16:00 From 21:30 to 23:00\nWeekends: Full access to the gym',
    ],
    priceMain: '€25',
    priceAccent: '/ Month',
    accentColor: Color(0xFFA7A7A7),
    amount: 25,
    billingPeriod: 'monthly',
  ),
  PlanModel(
    title: 'Youth Off-Peak\n12-Month Plan',
    markerColor: Color(0xFF45C83C),
    borderColor: Color(0xFF5A8755),
    background: LinearGradient(colors: [Color(0xFF15270E), Color(0xFF1C3112)]),
    bullets: [
      'Gift: 1 Pro Factory T-shirt',
      'For young people between 16 and 23 years of age',
      'Renewable subscription with a minimum commitment period of 12 months.',
      'Access to the gym at the following times:\nMonday to Friday: From 6:00 to 8:30 From 13:00 to 16:00 From 21:30 to 23:00\nWeekends: Full access to the gym',
    ],
    priceMain: '€20',
    priceAccent: '/ Month',
    accentColor: Color(0xFF45C83C),
    amount: 20,
    billingPeriod: 'monthly',
  ),
];
